import asyncio
import json
import logging
import os
import uuid
from pathlib import Path
from typing import Literal

from dotenv import load_dotenv
from langchain_core.exceptions import ModelError
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, MessagesState, StateGraph
from langgraph.prebuilt import ToolNode
from langgraph.types import Command, interrupt

load_dotenv()

# Hide harmless warnings about the "$schema" key generated by Zod in the MCP tool schemas
logging.getLogger("langchain_google_genai._function_utils").setLevel(logging.ERROR)

MCP_SERVER_PATH = Path(__file__).parent.parent / "-portfolio-mcp-server" / "src" / "server.js"
WRITE_TOOLS = {"add_project", "update_project"}

SYSTEM_PROMPT = (
    "Tu es un assistant qui gère le profil professionnel de Maryem Bannour. "
    "Utilise toujours les outils pour lire ou modifier les données, n'invente rien. "
    "Avant de modifier un projet existant, utilise list_projects pour trouver son id. "
    "Si l'utilisateur refuse une action, ne la réessaie pas. "
    "Réponds en français, de façon courte et claire."
)


class AgentState(MessagesState):
    verifications: list[str]  # results of post-write verifications


def tool_text(content) -> str:
    """Extract the text from an MCP tool result (str or list of content blocks)."""
    if isinstance(content, str):
        return content
    return "".join(b.get("text", "") for b in content if isinstance(b, dict))


# ---------- Routing ----------

def route_after_agent(state: AgentState) -> Literal["approval", "tools", "__end__"]:
    """After the LLM: end, run read tools directly, or ask for human approval on writes."""
    last = state["messages"][-1]
    if not getattr(last, "tool_calls", None):
        return END
    if any(call["name"] in WRITE_TOOLS for call in last.tool_calls):
        return "approval"
    return "tools"


def approval_node(state: AgentState) -> Command[Literal["tools", "agent"]]:
    """Pause the graph and ask the user to approve the write actions."""
    last = state["messages"][-1]
    actions = [
        {"outil": c["name"], "arguments": c["args"]}
        for c in last.tool_calls
        if c["name"] in WRITE_TOOLS
    ]
    decision = interrupt({"actions": actions})  # <- PAUSE: the graph waits here

    if decision == "oui":
        return Command(goto="tools")

    # Rejected: answer every pending tool call so the LLM knows nothing was executed
    refus = [
        ToolMessage(
            content="Action refusée par l'utilisateur.",
            tool_call_id=c["id"],
            name=c["name"],
        )
        for c in last.tool_calls
    ]
    return Command(goto="agent", update={"messages": refus})


# ---------- Building blocks ----------

async def load_mcp_tools():
    """Start the MCP server (stdio) and return its tools as LangChain tools."""
    client = MultiServerMCPClient({
        "portfolio": {
            "command": "node",
            "args": [str(MCP_SERVER_PATH)],
            "transport": "stdio",
        }
    })
    return await client.get_tools()


def create_llm():
    """Create the Gemini chat model from the .env configuration."""
    model_name = os.getenv("GEMINI_MODEL")
    if not model_name:
        raise ValueError("GEMINI_MODEL is missing in the .env file")
    return ChatGoogleGenerativeAI(
        model=model_name,
        max_retries=2,  # fail fast instead of retrying silently for minutes
        timeout=60,     # seconds: never wait forever for one LLM call
    )


# ---------- Graph construction ----------

def build_graph(llm, tools):
    """Build the agent graph. The LLM and tools are injected so tests can use fakes."""
    list_projects = next(t for t in tools if t.name == "list_projects")
    llm_with_tools = llm.bind_tools(tools)

    # Agent node: the LLM reads the history and decides (answer or call a tool)
    async def agent_node(state: AgentState):
        prompt = SYSTEM_PROMPT
        if state.get("verifications"):
            prompt += "\nVérifications effectuées : " + " | ".join(state["verifications"])
        response = await llm_with_tools.ainvoke([SystemMessage(prompt)] + state["messages"])
        return {"messages": [response]}

    # Verify node: never trust a "success" message, check the data itself
    async def verify_node(state: AgentState):
        """After a write, re-read the data to confirm the change was actually saved."""
        notes = []
        for msg in reversed(state["messages"]):
            if not isinstance(msg, ToolMessage):
                break  # only inspect results from the latest tool round
            if msg.name not in WRITE_TOOLS:
                continue
            try:
                data = json.loads(tool_text(msg.content))
            except json.JSONDecodeError:
                notes.append(f"{msg.name} : réponse illisible")
                continue
            if "error" in data:
                notes.append(f"{msg.name} a échoué : {data['error']}")
                continue
            project_id = data["project"]["id"]
            current = tool_text(await list_projects.ainvoke({}))
            if f'"{project_id}"' in current:
                notes.append(f"{msg.name} vérifié : le projet '{project_id}' est bien enregistré")
            else:
                notes.append(f"{msg.name} : le projet '{project_id}' est introuvable après écriture")
        return {"verifications": state.get("verifications", []) + notes}

    graph = StateGraph(AgentState)
    graph.add_node("agent", agent_node)
    graph.add_node("approval", approval_node)
    graph.add_node("tools", ToolNode(tools))
    graph.add_node("verify", verify_node)

    graph.add_edge(START, "agent")
    graph.add_conditional_edges("agent", route_after_agent)
    graph.add_edge("tools", "verify")
    graph.add_edge("verify", "agent")

    # The checkpointer persists state: required to pause and resume the graph
    return graph.compile(checkpointer=InMemorySaver())


# ---------- Conversation loop ----------

async def main():
    tools = await load_mcp_tools()
    agent = build_graph(create_llm(), tools)
    config = {"configurable": {"thread_id": str(uuid.uuid4())}}  # one thread = one conversation
    print("Agent prêt. Pose une question (ou 'q' pour quitter).\n")

    while True:
        question = input("Toi : ")
        if question.strip().lower() == "q":
            break

        try:
            result = await agent.ainvoke(
                {"messages": [HumanMessage(question)], "verifications": []}, config
            )

            # While the graph is paused, ask the user for approval
            while "__interrupt__" in result:
                for action in result["__interrupt__"][0].value["actions"]:
                    print(f"   ⚠️  L'agent veut exécuter {action['outil']} avec : {action['arguments']}")
                decision = input("   Tu confirmes ? (oui/non) : ").strip().lower()
                result = await agent.ainvoke(Command(resume=decision), config)

        except ModelError as error:
            # Any LLM error (quota 429, overload 503, unknown model 404...) must not crash the program
            print(f"   ❌ Erreur du modèle : {str(error)[:200]}\n")
            config = {"configurable": {"thread_id": str(uuid.uuid4())}}  # start a clean conversation
            continue

        for note in result.get("verifications", []):
            print(f"   [vérif] {note}")
        print(f"Agent : {result['messages'][-1].text}\n")


if __name__ == "__main__":
    asyncio.run(main())